# Generated by Django 3.2.9 on 2022-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embassy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('hours', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('location', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
