# Generated by Django 3.2.9 on 2022-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embassy',
            name='location',
            field=models.URLField(),
        ),
    ]
